version: '3'
services:
  # database:
  #   # Dockerfile이 있는 위치
  #   build: ./database
  #   # 내부에서 개방할 포트 : 외부에서 접근할 포트
  #   ports:
  #     - "3306:3306"
  backend:
    build: ./server
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    # # 환경변수 설정
    # environment: 
    #   - DBHOST=database
  frontend:
    build: ./client
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./frontend:/src
    ports:
      - "3000:3000"